import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ClientProvider } from "@/components/wrappers/ClientProvider";
import { NextIntlClientProvider } from "next-intl";
import { setRequestLocale } from "next-intl/server";
import ThemeRegistry from "@/theme/ThemeRegistry";
import { getThemeMode } from "@/theme/themeMode";
import { AppRouterCacheProvider } from "@mui/material-nextjs/v13-appRouter";
import { AvailableLanguage, languages } from "@myorg/shared/i18n";
import UserAuthProvider from "@/components/wrappers/auth/UserAuthProvider";
import { getUserAuth } from "@/utils/cache/user.cache.me";
import { GoogleOAuthProvider } from "@react-oauth/google";
import { AvailableMode } from "@/theme/theme";
import { redirect } from "@/i18n/navigation";
import { getHeaderValue } from "@/actions/headers.actions";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "market",
    description: "Generated by create next app",
};

type RootLayoutProps = {
    children: React.ReactNode;
    params: Promise<{ locale: string }>; // как даёт Next.js
};

export default async function RootLayout({
    children,
    params,
}: RootLayoutProps) {
    const { locale } = await params;

    const themeMode = await getThemeMode();

    const { user, error } = await getUserAuth();

    const newTheme = user?.theme || themeMode;

    setRequestLocale(locale as AvailableLanguage);

    return (
        <html className={newTheme} lang={locale}>
            <body
                style={{
                    display: "flex",
                    flexDirection: "column",
                    minHeight: "100vh",
                }}
                className={`${geistSans.variable} ${geistMono.variable} antialiased`}
            >
                <GoogleOAuthProvider
                    clientId={process.env.GOOGLE_CLIENT_ID as string}
                >
                    <NextIntlClientProvider>
                        <AppRouterCacheProvider
                            options={{ enableCssLayer: true }}
                        >
                            <ThemeRegistry
                                themeMode={newTheme as AvailableMode}
                            >
                                <UserAuthProvider error={error} user={user}>
                                    <ClientProvider>{children}</ClientProvider>
                                </UserAuthProvider>
                            </ThemeRegistry>
                        </AppRouterCacheProvider>
                    </NextIntlClientProvider>
                </GoogleOAuthProvider>
            </body>
        </html>
    );
}
