import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { MainProvider } from "@/app/[locale]/MainProvider";
import { NextIntlClientProvider } from "next-intl";
import { setRequestLocale } from "next-intl/server";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

type Params = Promise<{ locale: string }>;

type RootLayoutProps = {
    children: React.ReactNode;
    params: Params; // как даёт Next.js
};

export default async function RootLayout({
    children,
    params,
}: RootLayoutProps) {
    const { locale } = await params;

    console.log(locale);

    setRequestLocale(locale);

    return (
        <html lang={locale}>
            <body
                style={{
                    display: "flex",
                    flexDirection: "column",
                    minHeight: "100vh",
                }}
                className={`${geistSans.variable} ${geistMono.variable} antialiased`}
            >
                <NextIntlClientProvider>
                    <MainProvider>{children}</MainProvider>
                </NextIntlClientProvider>
            </body>
        </html>
    );
}
