import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { MainProvider } from "@/components/wrappers/ClientProvider";
import { NextIntlClientProvider } from "next-intl";
import { setRequestLocale } from "next-intl/server";
import ThemeRegistry from "@/theme/ThemeRegistry";
import { createTheme, InitColorSchemeScript } from "@mui/material";
import { getThemeMode } from "@/theme/themeMode";
import { AppRouterCacheProvider } from "@mui/material-nextjs/v13-appRouter";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

type Params = Promise<{ locale: string }>;

type RootLayoutProps = {
    children: React.ReactNode;
    params: Params; // как даёт Next.js
};

export default async function RootLayout({
    children,
    params,
}: RootLayoutProps) {
    const { locale } = await params;

    const themeMode = await getThemeMode();

    setRequestLocale(locale);

    return (
        <html
            style={
                {
                    // backgroundColor: themeConfig.palette?.primary?.main,
                }
            }
            lang={locale}
            suppressHydrationWarning
        >
            <body
                style={{
                    display: "flex",
                    flexDirection: "column",
                    minHeight: "100vh",
                    background: "transparent",
                }}
                className={`${geistSans.variable} ${geistMono.variable} antialiased`}
            >
                <NextIntlClientProvider>
                    <AppRouterCacheProvider options={{ enableCssLayer: false }}>
                        <ThemeRegistry themeMode={themeMode}>
                            <InitColorSchemeScript
                                defaultMode={themeMode}
                                attribute="class"
                            />
                            <MainProvider>{children}</MainProvider>
                        </ThemeRegistry>
                    </AppRouterCacheProvider>
                </NextIntlClientProvider>
            </body>
        </html>
    );
}
